# Generated by Django 4.1 on 2023-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(help_text='We take mail-id for username', max_length=20)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nmc_id', models.IntegerField(help_text='Enter your IMR registration number')),
                ('state', models.CharField(help_text="Which state's medical council?", max_length=15)),
                ('year', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
    ]
