# Generated by Django 4.1 on 2023-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email_id',
            field=models.EmailField(help_text='We take mail-id for username', max_length=50),
        ),
    ]
