# Generated by Django 4.1 on 2023-04-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_doctor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='nmc_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='year',
        ),
    ]
