# Generated by Django 4.1 on 2023-04-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_patient_remove_doctor_nmc_id_remove_doctor_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
