# Generated by Django 4.1 on 2023-04-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_rename_doctor_id_patient_doctor_remove_patient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(default=12200, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=31140, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
